### ISSUE TITLE
Sales summary files not updated in metadata

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/RealProp#34]
On the last update of the Sales_sum_* data sets on 3/16/17, the files were updated but metadata was not. This was because the _register =_ parameter was still set to _N_. But, this is an obsolete way of handling the updates. The code should be revised to use the _%Finalize_data_set()_ macro. 

Also, there was an error when creating the voter precinct summary data set.

`ERROR: [Summarize] Level (LEVEL=VOTERPRE2012) is not recognized.`

I'm not sure why this happened because it looks like VOTERPRE2012 is in the _$geoval._ format. @rpitingolo, would you please look into this?

**Comment by rpitingolo** [comment]
The summary programs now use %finalize_data_set so this shouldn't be a problem anymore.
