### ISSUE TITLE
Update parcel and sales data through 2017

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/RealProp#37]
Update the real property data files (Parcel_base, etc.), sales files (Sales_master, etc.) and sales summary files through 2017. 

@rpitingolo We received a request for these data, so please let me know when we think this update can be completed.

**Comment by ptatian** [comment]
@rpitingolo I’m getting pinged again about this. Any estimate on when it could be completed? Thanks.

**Comment by rpitingolo** [comment]
@ptatian I'll assign this out and get it done this week.

**Comment by rpitingolo** [comment]
@ptatian Noah is going to work on this update.

**Comment by ptatian** [comment]
Thank you!

**Comment by lhendey** [comment]
@rpitingolo - it doesn't look like this issue is complete? I don't see the updated metadata? Or is that another process that needs to be run. There are also 2 outstanding pull request in realprop?

**Comment by rpitingolo** [comment]
@lhendey I'll take a look .

**Comment by rpitingolo** [comment]
@lhendey @ptatian real property data is now fully up-to-date and updated macros will make this smooth sailing for future updates.
