### ISSUE TITLE
redo CAMA read-in

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/RealProp#43]

**Comment by lhendey** [comment]
@Woliver01 i've begun this process on enhancement-#43

Could you help me out by adding in the input statement and labels for these two data sets to Read_cama.sas in the Realprop /Macro folder. Save the raw data to  L:\Libraries\RealProp\Raw\2018-05.

These files do have different variables than the Res Pt file that I already did the code for.  If we meet briefly I can go over this with you. 

http://opendata.dc.gov/datasets/computer-assisted-mass-appraisal-commercial 
http://opendata.dc.gov/datasets/computer-assisted-mass-appraisal-condominium

**Comment by Woliver01** [comment]
@lhendey I can help with this.

**Comment by lhendey** [comment]
@Woliver01 have you been able to make any progress on this?

**Comment by Woliver01** [comment]
@lhendey I'm still having trouble getting it to run correctly. If you have time, do you think you could type up brief instructions on this issue?

**Comment by lhendey** [comment]
@Woliver01 - can you commit what ever you've done?

**Comment by lhendey** [comment]
@Woliver01 
The Read_cama macro you are editing should have three separate data steps (one for each cama type) between the %macro and %mend when you are done. 

To test how your coding is going open: 
D:\DCDATA\Libraries\Realprop\Prog\Updates\Read_CAMA_2018_05.sas

and run the following - look at the log to see how it's going. 

%include "L:\SAS\Inc\StdLocal.sas";

** Define libraries **;
%DCData_lib( RealProp )


%let filedate=2018-05; 

/*Read in raw cama files*/
%Read_cama;

**Comment by lhendey** [comment]
@Woliver01 - if you have the macro open in sas and you are editing it (vs. editing it in github or textpad or something) you do need to rerun the code start to finish before trying to test it or you won't get any of the updates.

**Comment by Woliver01** [comment]
@lhendey I ran it and got a ton of warnings, specifically WARNING: Invalid sale date. I made sure to close the macros.

**Comment by lhendey** [comment]
@Woliver01 - did you put the original residential code bacK?

**Comment by Woliver01** [comment]
@lhendey I think I'm understanding it better. I'll commit the changes before I leave and you can look them over them whenever you get the chance.
