### ISSUE TITLE
Property step 4: Updating Sales Files

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/RealProp#62]
Instructions: https://urbanorg.app.box.com/file/133443052372

**Comment by ptatian** [comment]
@rpitingolo @Woliver01 I was working with the real property data recently and discovered that, when the last real property update was done in September, no one ever batch submitted **L:\Libraries\Realprop\Prog\Updates\Update_sales_2018_09.sas**  As a result, the sales data sets were not updated. 

The issue should not be closed until the batch submit is done and you have confirmed that it ran properly.

Please batch submit these programs to complete the update:

- [ ] Prog\Updates\Update_sales_2018_09.sas
- [ ] Prog\Updates\Sales_sum_all.sas

Thank you.

**Comment by Woliver01** [comment]
@rpitingolo Hi Rob, I ran these just now. Please take a look when you get a chance and let me know if everything looks right.

**Comment by rpitingolo** [comment]
@Woliver01 thanks. when you say you ran them do you mean on your D drive?

**Comment by Woliver01** [comment]
@rpitingolo I ran them on the L drive.

**Comment by rpitingolo** [comment]
@Woliver01 thanks, Will. 
@ptatian this is now complete. I manually refreshed the metadata and it looks like everything got updated.
