### ISSUE TITLE
Property step 5: Updating Summary Files

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/RealProp#63]
Instructions: https://urbanorg.app.box.com/file/295567911944

**Comment by Woliver01** [comment]
@rpitingolo steps 1-10 I already did for this part of the update. Should I just continue to step 11?

**Comment by rpitingolo** [comment]
@Woliver01 yes please do that. I need to update the instructions so they are not duplicate.

**Comment by Woliver01** [comment]
@rpitingolo this step is complete.

**Comment by rpitingolo** [comment]
@Woliver01 thanks for your work on this. I'm going to close all the issues now.
