### ISSUE TITLE
Update RealProp data for Q3-2016

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/RealProp#7]

**Comment by rpitingolo** [comment]
@ptatian @lhendey I'd like to get this data updated before Thanksgiving. Am I good to use the new Cafritz money for it?

**Comment by lhendey** [comment]
I think Peter wants to use up some internal funds. He’ll let you know which account.

**Comment by ptatian** [comment]
Yes, please use 00741-010-02. Thanks, Rob!






On Tue, Nov 15, 2016 at 9:32 AM -0500, "Leah Hendey" <notifications@github.com<mailto:notifications@github.com>> wrote:

I think Peter wants to use up some internal funds. He’ll let you know which account.

**Comment by rpitingolo** [comment]
Merged and closed.
